
DROP TABLE IF EXISTS GenesysCloud_ENCUESTA_NPS;
GO
CREATE TABLE GenesysCloud_ENCUESTA_NPS
(
S_ID INT IDENTITY(1,1),
S_FECHA_INSERCION DATETIME DEFAULT GETDATE(),
S_FECHA_CONVERSACION NVARCHAR(255),
S_ID_CONVERSACION NVARCHAR(255),
S_COLA NVARCHAR(255),
S_TELEFONO NVARCHAR(255),
S_AGENTE_ID NVARCHAR(255),
S_AGENTE_EMAIL NVARCHAR(255),
S_PREGUNTA_CATEGORIA NVARCHAR(255),
S_PREGUNTA_DESCRIPCION NVARCHAR(255),
S_RESPUESTA_VALOR NVARCHAR(255),
S_RESPUESTA_DESCRIPCION NVARCHAR(255),
S_AUX01 NVARCHAR(255),
S_AUX02 NVARCHAR(255),
S_AUX03 NVARCHAR(255)
)
GO

ALTER TABLE GenesysCloud_ENCUESTA_NPS ADD PRIMARY KEY CLUSTERED (S_ID)
GO


