
GO
DROP TABLE IF EXISTS GenesysCloud_LOG_PROCESS;
GO
CREATE TABLE GenesysCloud_LOG_PROCESS(
	S_ID INT IDENTITY(1,1),
	S_INSERT_DATE  DATETIME DEFAULT GETDATE(),
	S_STATE NVARCHAR(255) ,
	S_ERROR_NUMBER NVARCHAR(255) ,
	S_SCHEMA NVARCHAR(255) ,
	S_NAME_PROCEDURE NVARCHAR(255) ,
	S_ERROR_LINE NVARCHAR(255) ,
	S_MESSAGE NVARCHAR(255) 

) 

GO
ALTER TABLE GenesysCloud_LOG_PROCESS ADD PRIMARY KEY CLUSTERED (S_ID)
GO

