
DROP PROCEDURE IF EXISTS GenesysCloud_API_InsertEncuestaNps;
GO
CREATE PROCEDURE GenesysCloud_API_InsertEncuestaNps
@S_FECHA_CONVERSACION NVARCHAR(255),
@S_ID_CONVERSACION NVARCHAR(255),
@S_COLA NVARCHAR(255),
@S_TELEFONO NVARCHAR(255),
@S_AGENTE_ID NVARCHAR(255),
@S_AGENTE_EMAIL NVARCHAR(255),
@S_PREGUNTA_CATEGORIA NVARCHAR(255),
@S_PREGUNTA_DESCRIPCION NVARCHAR(255),
@S_RESPUESTA_VALOR NVARCHAR(255),
@S_RESPUESTA_DESCRIPCION NVARCHAR(255),
@S_AUX01 NVARCHAR(255),
@S_AUX02 NVARCHAR(255),
@S_AUX03 NVARCHAR(255)

AS SET NOCOUNT ON;

BEGIN
	BEGIN TRY
		INSERT INTO GenesysCloud_ENCUESTA_NPS(S_FECHA_INSERCION,S_FECHA_CONVERSACION,S_ID_CONVERSACION,S_COLA,S_TELEFONO,S_AGENTE_ID,S_AGENTE_EMAIL,S_PREGUNTA_CATEGORIA,S_PREGUNTA_DESCRIPCION,S_RESPUESTA_VALOR,S_RESPUESTA_DESCRIPCION,S_AUX01,S_AUX02,S_AUX03)
		VALUES(GETDATE(),@S_FECHA_CONVERSACION,@S_ID_CONVERSACION,@S_COLA,@S_TELEFONO,@S_AGENTE_ID,@S_AGENTE_EMAIL,@S_PREGUNTA_CATEGORIA,@S_PREGUNTA_DESCRIPCION,@S_RESPUESTA_VALOR,@S_RESPUESTA_DESCRIPCION,@S_AUX01,@S_AUX02,@S_AUX03)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	END TRY
	BEGIN CATCH
		INSERT GenesysCloud_LOG_PROCESS (S_INSERT_DATE,S_STATE,S_ERROR_NUMBER,S_SCHEMA,S_NAME_PROCEDURE,S_ERROR_LINE,S_MESSAGE)
		VALUES (GETDATE(),'ERROR',ERROR_NUMBER(),'DBO',ERROR_PROCEDURE(),ERROR_LINE(),ERROR_MESSAGE())	
	END CATCH

END